from typing import Any

def all_subclasses(cls, seen = None):
    """Recursive (preorder) enumeration of all subclasses

    :param cls: the parent class to recurse from
    :type cls: class
    :param seen: A set containing already seen classes, which helps with the recursion.
        defaults to None
    :type seen: set, optional
    :yield: Each subclass as it is encountered
    :rtype: class
    """
    # create shared set for each new call because 
    # default args are evaluated only once (at definition):
    if seen == None:
        seen = set()

    # yield class before recursing (preorder)
    # only ever called on unseen classes, so no check to seen is necessary
    seen.add(cls)
    yield cls

    # only yield for types in which subclasses is a real method:
    if type(cls.__subclasses__) == type(object.__subclasses__):
        # yield all descendents recursively
        for child in cls.__subclasses__():
            if child not in seen:
                for descendent in all_subclasses(child, seen):
                    yield descendent

def generate_JSON(
    *objs: Any
) -> dict[str,Any]:
    """Given a set of objects, generate a JSON file which stores their information.

    The exact structure of the JSON encoding is determined by the conventions of the
    '_generate_JSON_entry' and '_parse_JSON_entry' methods in each stored class. In 
    addition, some metadata (such as the class name and id number) are stored, which 
    help the parse methods reference the relations between objects, and identify the 
    right class to use when reconstructing. A list storing the ids to return helps the
    return of the parse match the structure of the input list.

    :param obj: A variable number of objects to store into the JSON file
    :type: Any
    :return: The JSON object encoding the data of the input
    :rtype: dict[str, Any]
    """
    # Create the ids:
    obj_ids = {}
    for o in objs:
        # every object needs to specify it's IDs for this to work
        obj_ids = o.generate_ids(obj_ids)
    
    # create the json:
    num_objs = max(obj_ids.values()) + 1
    obj_entries: list[Any] = [None for i in range(num_objs)]
    for obj, id in obj_ids.items():
        obj_entries[id] = {
            'index': obj_ids[obj], # just for human readability
            'class': str(obj.__class__)[8:-2],
            'data': obj._generate_JSON_entry(obj_ids)
        }
        
    # Annotate with return order:
    return {
        "objects": obj_entries,
        "return order": [obj_ids[obj] for obj in objs]
    }

def parse_JSON(json_object: dict[str,Any]) -> tuple[Any]:
    """Parses a JSON object back into the BooleanFunctions which generated it.

    This method is paired with `generate_JSON`. This method is able to reverse the Generated
    JSON back into an equivalent structure. A list storing the ids to return helps the returned tuple
    to match the structure of the input list, so that objects are reconstructed in the same way they
    are stored.

    :json_object: A dictionary with the structure generated by `generate_JSON`
    :type: dict[str,Any]
    :return: A tuple of objects parsed from the JSON.
    :rtype: tuple[Any]
    """
    # get current classes to reconstruct
    class_mapping = {
        str(cls)[8:-2]: cls
        for cls in all_subclasses(object)
    }

    # parse object class and data
    return_ids = json_object["return order"]
    json_obj_list = json_object["objects"]
    num_nodes = len(json_obj_list)
    parsed_objects: list[Any] = [None for i in range(num_nodes)]
    for id in range(num_nodes):
        obj_json = json_obj_list[id]
        
        # create information for the python object for this node
        object_data = obj_json['data']
        if obj_json['class'] in class_mapping:
            object_class: Any = class_mapping[obj_json['class']]
        else:
            print([x for x in class_mapping.keys() if x[:4] == "PyPR"])
            print("PyPR.FeedbackRegister.FeedbackRegister" in class_mapping)
            raise TypeError(f"Type \'{obj_json['class']}\' not recognized.")

        # stuff data into new object and add it to the parsed list
        parsed_objects[id] = object_class._parse_JSON_entry(
            object_data, parsed_objects
        )
    
    # return the given objects:
    return tuple([parsed_objects[node_id] for node_id in return_ids])
