from ProductRegisters.BooleanLogic.ChainingGeneration.Templates.arman_template import arman_template
from ProductRegisters.BooleanLogic.ChainingGeneration.Templates.three_majority_template import three_majority_template
from ProductRegisters.BooleanLogic.ChainingGeneration.Templates.old_ANF_template import old_ANF_template
from ProductRegisters.BooleanLogic.ChainingGeneration.Templates.simple_template import simple_template
