"""Tests for the Berlekamp-Massey algorithm and its iterator variant.

BM recovers the shortest LFSR that generates a given binary sequence.  The
tests here verify:
  - Correct polynomial recovery from known m-sequences.
  - The linear-complexity / recurrence relationship.
  - The iterator variant yields non-decreasing LC values and agrees with
    the batch version on the full sequence.
"""
import numpy as np

from PyPR.FeedbackRegister import FeedbackRegister
from PyPR.FeedbackFunctions import MPR
from PyPR.Tools.RegisterSynthesis.lfsrSynthesis import berlekamp_massey, berlekamp_massey_iterator


# ── Helpers ───────────────────────────────────────────────────────────────────

def _mpr_seq(size: int, koopman: str, length: int) -> list[int]:
    """Generate `length` bits from bit-0 of an MPR with the given parameters."""
    M = MPR(size, koopman)
    reg = FeedbackRegister(2**size - 1, M)
    return [state[0] for state in reg.run(length, compiled=False)]


# ── Polynomial recovery ────────────────────────────────────────────────────────

def test_bm_recovers_degree3_poly():
    """BM on a degree-3 m-sequence returns LC=3.

    The connection polynomial recovered by BM is the reciprocal of the
    primitive polynomial stored by the MPR (because the MPR uses a
    'shift-up' convention rather than 'shift-down').  We verify LC only here;
    the convolution recurrence test verifies the polynomial's correctness.
    """
    seq = _mpr_seq(3, "5", 20)
    lc, _ = berlekamp_massey(seq)
    assert lc == 3, f"Expected LC=3, got {lc}"

def test_bm_recovers_degree5_poly():
    """BM on a degree-5 m-sequence returns LC=5."""
    seq = _mpr_seq(5, "12", 30)
    lc, _ = berlekamp_massey(seq)
    assert lc == 5, f"Expected LC=5, got {lc}"

def test_bm_recovers_degree7_poly():
    """BM on a degree-7 m-sequence returns LC=7."""
    seq = _mpr_seq(7, "65", 30)
    lc, _ = berlekamp_massey(seq)
    assert lc == 7, f"Expected LC=7, got {lc}"


# ── Monic polynomial ──────────────────────────────────────────────────────────

def test_bm_polynomial_is_monic():
    """BM always returns a monic polynomial (poly[0] == 1)."""
    seq = _mpr_seq(5, "12", 30)
    _, poly = berlekamp_massey(seq)
    assert poly[0] == 1, f"Expected monic polynomial, but poly[0]={poly[0]}"


# ── Recurrence check ─────────────────────────────────────────────────────────

def test_bm_polynomial_satisfies_recurrence():
    """The returned polynomial P convolves with the sequence to all-zeros past degree L.

    For a sequence generated by an LFSR with polynomial P of degree L,
    convolving the first N + L bits of the sequence with P must give zeros
    at positions L, L+1, ..., N-1 (beyond the transient region).
    """
    seq = _mpr_seq(5, "12", 30)
    lc, poly = berlekamp_massey(seq)
    arr = np.array(seq, dtype=np.uint8)
    convolved = np.convolve(arr, poly) % 2
    # All positions from lc onward (the purely-recurrent region) must be 0
    assert np.all(convolved[lc:len(seq)] == 0), (
        f"Recurrence not satisfied; non-zero at: {np.where(convolved[lc:len(seq)] != 0)}"
    )

def test_bm_recurrence_for_degree3():
    """Recurrence check for degree-3 m-sequence."""
    seq = _mpr_seq(3, "5", 20)
    lc, poly = berlekamp_massey(seq)
    arr = np.array(seq, dtype=np.uint8)
    convolved = np.convolve(arr, poly) % 2
    assert np.all(convolved[lc:len(seq)] == 0)


# ── Linear complexity bound ───────────────────────────────────────────────────

def test_bm_lc_at_most_half_sequence():
    """For a sequence of length N, LC <= N/2 (uniqueness region)."""
    seq = _mpr_seq(7, "65", 50)
    lc, _ = berlekamp_massey(seq)
    assert lc <= len(seq) / 2, f"LC={lc} exceeds N/2={len(seq)/2}"


# ── All-zeros sequence ────────────────────────────────────────────────────────

def test_bm_all_zeros_gives_lc_zero():
    """A constant-zero sequence has linear complexity 0."""
    seq = [0] * 20
    lc, _ = berlekamp_massey(seq)
    assert lc == 0


# ── Iterator variant ──────────────────────────────────────────────────────────

def test_bm_iterator_final_matches_batch():
    """The last value yielded by berlekamp_massey_iterator matches the batch result."""
    seq = _mpr_seq(5, "12", 40)
    lc_batch, poly_batch = berlekamp_massey(seq)

    last_lc = last_poly = None
    for lc_iter, poly_iter in berlekamp_massey_iterator(iter(seq), yield_rate=10):
        last_lc, last_poly = lc_iter, poly_iter

    assert last_lc == lc_batch, f"Iterator LC {last_lc} != batch LC {lc_batch}"
    assert list(last_poly) == list(poly_batch), "Iterator polynomial != batch polynomial"

def test_bm_iterator_lc_is_nondecreasing():
    """LC values emitted by the iterator never decrease."""
    seq = _mpr_seq(7, "65", 60)
    prev_lc = 0
    for lc, _ in berlekamp_massey_iterator(iter(seq), yield_rate=8):
        assert lc >= prev_lc, f"LC decreased from {prev_lc} to {lc}"
        prev_lc = lc

def test_bm_iterator_yields_multiple_chunks():
    """The iterator yields at least one intermediate result before the final one."""
    seq = _mpr_seq(5, "12", 40)
    results = list(berlekamp_massey_iterator(iter(seq), yield_rate=10))
    assert len(results) >= 2, "Expected multiple iterator yields"
